version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: stock-postgres
    environment:
      POSTGRES_DB: stock_market
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stock-network

  redis:
    image: redis:7-alpine
    container_name: stock-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - stock-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/stock_market
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - stock-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data:

networks:
  stock-network:
    driver: bridge