version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: stock-postgres-dev
    environment:
      POSTGRES_DB: stock_market_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - stock-network

  redis:
    image: redis:7-alpine
    container_name: stock-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes
    networks:
      - stock-network

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  stock-network:
    driver: bridge